import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bezy — Privacy Policy",
  description: "Privacy Policy for the Bezy app on Pi Network.",
};

/**
 * Generated from the Telegram app's privacy policy so the two stay in step.
 * Only the facts that differ between the networks are changed.
 */
export default function PrivacyPolicy() {
  return (
    <main className="mx-auto w-full max-w-[760px] px-4 py-8 text-bz-ink">
      <h1 className="font-display text-3xl font-bold tracking-tight">Privacy Policy</h1>
      <p className="mt-1 text-xs text-bz-muted">Effective date: 10 September 2026</p>
      <p className="mt-6 text-sm leading-relaxed text-bz-muted">Bezy is a Pi-native service. The Bezy app runs inside Pi Browser and signs you in with your Pi account, while Bezy services are operated through Vercel and a server-side PostgreSQL database hosted by Neon.</p>
      <h2>1. Who is responsible for your data?</h2>
      <p>Bezy is operated by <strong>DIGITAL CONCORDIA</strong>, a business registered in Benin under Registration No. <strong>RB/ABC/21 A 28773</strong>, registered on 25 March 2021 with the Cotonou Commercial Court, and represented by its owner and legal representative, Yao Sossou. Registered address: <strong>Abomey-Calavi, Benin</strong>. Digital Concordia is the operating and trade name used for Bezy; the underlying business registration number is RB/ABC/21 A 28773. You can contact us at <strong>contacts@digitalconcordia.com</strong>.</p>
      <h2>2. What information we collect</h2>
      <p>When you use Bezy through Pi, we receive your Pi user identifier (UID) and username. We do not receive your Pi password, and we do not receive any personal details from Pi beyond those two values. We also process information you choose to provide in your Bezy profile: age, gender, who you are looking for, the area or city you enter (we do not use GPS or precise location), interests, a short bio, and the dating photos you add. We also process likes, passes, matches, messages, membership status, reports and moderation information, the operational counters needed for rate limiting and abuse protection, and any support requests you send us.</p>
      <h2>3. Messages</h2>
      <p>Bezy is designed so that conversations between matches take place inside Bezy. When two people match, they can message each other within the Mini App. Bezy stores those messages and their read state so both participants can see the conversation. A conversation closes when the match ends or when either of you blocks the other; messaging stops, and deleting your Bezy account deletes your conversations and their messages. When you ask Bezy support for help, the description you send is stored with your support request (capped at 1000 characters) and is deleted with your account.</p>
      <h2>4. One Bezy community</h2>
      <p>Bezy is a single community with two ways in. When you create a Bezy profile, it is published to Bezy’s shared community service and can be discovered by other members on either network — people using the Pi app and people using the Telegram Mini App see the same pool of profiles, and a match or conversation can be with someone on the other network. Nothing tells another member which network you joined through. What is shared is your dating profile (display name, age, gender, area you enter, interests, bio, looking-for), your dating photos, and your likes, passes, matches, messages, blocks and reports. Your Pi identity itself — your Pi UID and username — is never shown to another member; they see only the profile you chose to publish.</p>
      <h2>5. Photos</h2>
      <p>Dating photos you add are stored in a private Vercel Blob store, with a reference held in Bezy’s shared database. They are never stored in the database itself and are not publicly readable: another member can only load a photo through a server-authenticated request, and only when Bezy’s access rules allow it for that person. A copy may be cached on a viewer’s own device, so a copy already viewed cannot be recalled from that device — deleting the photo stops any further access but cannot erase a copy someone already has. Your Pi profile picture is not used by Bezy; the photos you add in Bezy are the ones other members see.</p>
      <h2>6. Why we use your information</h2>
      <p>We use information to authenticate you through Pi, create and maintain your Bezy profile, provide discovery and matching, operate matches and notifications (including optional profile-reminders — at most one per week, which you can switch off), provide paid features, prevent abuse and fraud, enforce our rules, answer support requests, improve reliability, and comply with legal obligations.</p>
      <h2>7. Legal bases</h2>
      <p>For users in the European Economic Area, processing may rely on performance of the service contract, your consent where consent is required, our legitimate interests in security and service operation, and legal obligations. Where we rely on consent, you may withdraw it as described in the service or by contacting us.</p>
      <h2>8. Service providers</h2>
      <p>Bezy currently uses Pi Network for sign-in and for payment processing; Vercel for hosting, serverless API execution and private photo storage; and Neon as the provider of the managed server-side PostgreSQL database. The Bezy app has no direct access to the database or to the photo store.</p>
      <h2>9. Payments</h2>
      <p>Bezy Premium is paid in Pi. Payment is handled by Pi Network’s own payment flow, shown to you inside the Pi app: Bezy never sees your wallet credentials or any card details, and Bezy cannot charge you without your approval of each payment. Bezy’s server checks every payment against Pi’s Platform API before Premium is granted, and records the payment identifier, plan, amount and dates so the entitlement survives a reinstall. Premium is a one-off payment for a fixed period, not an automatic subscription. Additional payment information is governed by the applicable Pi Network terms.</p>
      <h2>10. Data retention</h2>
      <p>We retain personal data only for as long as reasonably necessary for the purposes described above, including account operation, safety, dispute handling and legal obligations. Bezy already applies defined deletion schedules for operational data: incomplete accounts with no activity are removed after about 90 days, ended matches after about 180 days, spent invoice links after 30 days, rate-limit counters after 7 days, and support requests after 365 days unless you delete your account first. Payment records and safety reports are kept until their retention periods are confirmed by legal and accounting review — the deletion mechanism exists, but those periods are deliberately not set yet. These schedules are applied by an operator-run tool; Bezy does not run an automatic scheduler.</p>
      <h2>11. Your rights</h2>
      <p>Depending on applicable law, you may have rights to access, correct, delete, restrict or object to processing, and to receive a portable copy of certain data. Four of these are built into Bezy and you can use them yourself at any time: open Bezy, go to Profile, then Privacy &amp; your data. <strong>Download my data</strong> gives you a machine-readable copy of your Bezy account, profile, preferences, notification settings, decisions, blocks, matches, support requests and payment records. <strong>Pause processing</strong> restricts processing: we keep your data but stop using it, your profile leaves Discover, you cannot like or match, and we stop sending you match and Super Like messages. Nothing is deleted and you can lift it yourself at any time. <strong>Object to processing</strong> lets you exercise your right to object: we stop using your data for discovery and matching, nothing is deleted, and you can withdraw the objection yourself at any time. <strong>Delete my account</strong> permanently removes your profile, your likes and passes, your blocks and your support requests, and ends your matches. For any other request, or to complain to your local data protection authority, contact <strong>contacts@digitalconcordia.com</strong>. We aim to answer within 3 working days. We may need to verify that a request relates to the correct account.</p>
      <h2>12. Children</h2>
      <p>Bezy is intended for adults aged 18 and over. Before using Bezy, each person must explicitly declare that they are 18 or older; we store that declaration, the time it was made, and the fact that it is a self-declaration. Bezy does not verify identity or age, and does not claim its users are verified adults. We do not knowingly allow minors to create or use dating profiles. If you believe a minor is using Bezy, contact us at <strong>contacts@digitalconcordia.com</strong>.</p>
      <h2>13. Security</h2>
      <p>We use reasonable technical and organisational measures to protect Bezy data. Pi access tokens are validated server-side against the Pi Platform API before they are trusted. The Mini App has no direct database access; server-side access uses authenticated credentials held in Vercel environment variables.</p>
      <h2>14. Changes</h2>
      <p>We may update this policy when Bezy changes or when legal requirements change. The effective date at the top will identify the current version. Material changes will be communicated through Bezy where appropriate.</p>
      <h2>15. Safety, blocking and reporting</h2>
      <p>If you block someone in Bezy, we record that block so neither of you appears to the other in discovery and neither can like or match the other. If you report someone, we store who reported whom, the reason you selected, any description you write, a status and any moderation note, so that a person can review it. We do not copy the reported profile into the report. Reports are kept even if either account is deleted, so a record of conduct cannot be erased by the person responsible for it. Blocking and reporting take effect across the whole Bezy community, on both networks: the person cannot see you, message you or match with you anywhere in Bezy.</p>
      <h2>16. Deleting your account</h2>
      <p>You can delete your Bezy account at any time from Profile then Privacy &amp; your data. This removes your profile, your discovery preferences, your likes, passes and super likes, the record of who liked you, your blocks and your support requests, and it ends your matches. Four things are deliberately kept: records of payments you made, retained to meet accounting obligations, containing only a Pi identifier, a plan, an amount and dates; the invoice links belonging to those payments; and reports — both those you filed and those filed about you, so a record of conduct cannot be erased by the person responsible for it. Deleting your Bezy account does not delete your Pi account.</p>
      <h2>17. How matching works</h2>
      <p>Bezy first filters who you can see: your profile must be complete and visible, both people must meet each other’s age range and “looking for” settings, and neither may have blocked, paused or already decided on the other. Among eligible profiles, Bezy orders what you see with a simple, fixed calculation: a base value, plus points for interests you share, a shared spoken language, being in the same city, closeness in age, and a small bonus for a completed bio. Premium members receive a small fixed boost in that ordering. The score only changes order — it is computed only from what both people wrote in their own profiles, it never decides anything about you, and every like or pass is your own decision. Premium members can also see why a score is what it is, using the same on-profile facts. There is no artificial intelligence and no hidden profiling.</p>
      <p className="mt-8 text-xs leading-relaxed text-bz-faint">
        Contact: contacts@digitalconcordia.com — we aim to answer within 3 working days.
      </p>
    </main>
  );
}
